// CRITICAL GAPS DATA - Skills completely missing from user
export const CRITICAL_GAPS_POOL = [
  {
    id: "cg1",
    name: "Docker & Containerization",
    category: "DevOps",
    gapSeverity: "High",
    marketDemand: 95,
    description: "Container orchestration essential for modern cloud infrastructure deployment",
    estimatedLearningTime: "2-3 months",
    priority: "Critical",
    salaryImpact: "₹4.2L - ₹5.5L",
    learningTime: "2-3 months",
    jobPostings: "2845",
  },
  {
    id: "cg2",
    name: "Kubernetes",
    category: "DevOps",
    gapSeverity: "High",
    marketDemand: 92,
    description: "Container orchestration platform for scalable applications and microservices",
    estimatedLearningTime: "3-4 months",
    priority: "Critical",
    salaryImpact: "₹4.5L - ₹5.8L",
    learningTime: "3-4 months",
    jobPostings: "2156",
  },
  {
    id: "cg3",
    name: "CI/CD Pipeline",
    category: "DevOps",
    gapSeverity: "High",
    marketDemand: 88,
    description: "Automated deployment processes critical for modern development workflows",
    estimatedLearningTime: "2-3 months",
    priority: "High",
    salaryImpact: "₹3.8L - ₹5.0L",
    learningTime: "2-3 months",
    jobPostings: "1934",
  },
  {
    id: "cg4",
    name: "Terraform",
    category: "Infrastructure",
    gapSeverity: "High",
    marketDemand: 85,
    description: "Infrastructure as code for cloud provisioning and management",
    estimatedLearningTime: "2-3 months",
    priority: "High",
    salaryImpact: "₹3.5L - ₹4.8L",
    learningTime: "2-3 months",
    jobPostings: "1678",
  },
  {
    id: "cg5",
    name: "Monitoring & Observability",
    category: "DevOps",
    gapSeverity: "Medium",
    marketDemand: 82,
    description: "Application monitoring, logging, and distributed tracing systems",
    estimatedLearningTime: "2-3 months",
    priority: "High",
    salaryImpact: "₹3.2L - ₹4.5L",
    learningTime: "2-3 months",
    jobPostings: "1456",
  },
  {
    id: "cg6",
    name: "AWS/Azure/GCP",
    category: "Cloud",
    gapSeverity: "High",
    marketDemand: 95,
    description: "Cloud platform expertise for infrastructure and service management",
    estimatedLearningTime: "3-4 months",
    priority: "Critical",
    salaryImpact: "₹4.8L - ₹6.2L",
    learningTime: "3-4 months",
    jobPostings: "3245",
  },
  {
    id: "cg7",
    name: "System Design",
    category: "Architecture",
    gapSeverity: "High",
    marketDemand: 90,
    description: "Design scalable distributed systems for enterprise applications",
    estimatedLearningTime: "4-6 months",
    priority: "Critical",
    salaryImpact: "₹5.0L - ₹6.5L",
    learningTime: "4-6 months",
    jobPostings: "2678",
  },
  {
    id: "cg8",
    name: "Microservices Architecture",
    category: "Architecture",
    gapSeverity: "High",
    marketDemand: 87,
    description: "Distributed system design for scalable and resilient applications",
    estimatedLearningTime: "3-5 months",
    priority: "High",
    salaryImpact: "₹4.2L - ₹5.5L",
    learningTime: "3-5 months",
    jobPostings: "1923",
  },
  {
    id: "cg9",
    name: "GraphQL",
    category: "Backend",
    gapSeverity: "Medium",
    marketDemand: 78,
    description: "Modern API query language for flexible data fetching",
    estimatedLearningTime: "1-2 months",
    priority: "High",
    salaryImpact: "₹3.0L - ₹4.2L",
    learningTime: "1-2 months",
    jobPostings: "1245",
  },
  {
    id: "cg10",
    name: "Security & Authentication",
    category: "Security",
    gapSeverity: "High",
    marketDemand: 92,
    description: "OAuth, JWT, and modern authentication and security patterns",
    estimatedLearningTime: "2-3 months",
    priority: "Critical",
    salaryImpact: "₹4.0L - ₹5.3L",
    learningTime: "2-3 months",
    jobPostings: "2134",
  },
  {
    id: "cg11",
    name: "Message Queues (Kafka/RabbitMQ)",
    category: "Backend",
    gapSeverity: "Medium",
    marketDemand: 80,
    description: "Asynchronous processing and event streaming architecture",
    estimatedLearningTime: "2-3 months",
    priority: "High",
    salaryImpact: "₹3.5L - ₹4.8L",
    learningTime: "2-3 months",
    jobPostings: "1567",
  },
  {
    id: "cg12",
    name: "Testing & TDD",
    category: "Software Engineering",
    gapSeverity: "Medium",
    marketDemand: 85,
    description: "Test-driven development and comprehensive testing strategies",
    estimatedLearningTime: "2-3 months",
    priority: "High",
    salaryImpact: "₹3.2L - ₹4.5L",
    learningTime: "2-3 months",
    jobPostings: "1834",
  },
  {
    id: "cg13",
    name: "NoSQL Databases (MongoDB)",
    category: "Database",
    gapSeverity: "Medium",
    marketDemand: 80,
    description: "NoSQL database for handling unstructured and semi-structured data",
    estimatedLearningTime: "2-3 months",
    priority: "Medium",
    salaryImpact: "₹3.0L - ₹4.2L",
    learningTime: "2-3 months",
    jobPostings: "1456",
  },
  {
    id: "cg14",
    name: "Redis & Caching",
    category: "Backend",
    gapSeverity: "Medium",
    marketDemand: 82,
    description: "In-memory caching for performance optimization and real-time data",
    estimatedLearningTime: "1-2 months",
    priority: "Medium",
    salaryImpact: "₹2.8L - ₹4.0L",
    learningTime: "1-2 months",
    jobPostings: "1245",
  },
  {
    id: "cg15",
    name: "WebSocket & Real-time Communication",
    category: "Backend",
    gapSeverity: "Low",
    marketDemand: 75,
    description: "Real-time bidirectional communication for live applications",
    estimatedLearningTime: "1-2 months",
    priority: "Medium",
    salaryImpact: "₹2.5L - ₹3.8L",
    learningTime: "1-2 months",
    jobPostings: "945",
  },
]

// SKILLS TO IMPROVE DATA - Skills user has but below target proficiency
export const SKILLS_TO_IMPROVE_POOL = [
  {
    id: "si1",
    name: "TypeScript",
    category: "Programming",
    currentLevel: "Beginner",
    targetLevel: "Intermediate",
    priority: "High",
    estimatedTime: "2-3 months",
    description: "Strongly-typed JavaScript for large-scale applications",
    marketDemand: 92,
    proficiency: 2,
  },
  {
    id: "si2",
    name: "React",
    category: "Frontend",
    currentLevel: "Intermediate",
    targetLevel: "Advanced",
    priority: "High",
    estimatedTime: "2-3 months",
    description: "Modern frontend framework with hooks and advanced patterns",
    marketDemand: 95,
    proficiency: 3,
  },
  {
    id: "si3",
    name: "Node.js",
    category: "Backend",
    currentLevel: "Beginner",
    targetLevel: "Intermediate",
    priority: "High",
    estimatedTime: "2-3 months",
    description: "JavaScript runtime for backend development",
    marketDemand: 90,
    proficiency: 2,
  },
  {
    id: "si4",
    name: "SQL Optimization",
    category: "Database",
    currentLevel: "Beginner",
    targetLevel: "Intermediate",
    priority: "Medium",
    estimatedTime: "1-2 months",
    description: "Query optimization and database performance tuning",
    marketDemand: 78,
    proficiency: 2,
  },
  {
    id: "si5",
    name: "AWS Lambda",
    category: "Cloud",
    currentLevel: "Beginner",
    targetLevel: "Intermediate",
    priority: "High",
    estimatedTime: "2-3 months",
    description: "Serverless computing and Lambda functions",
    marketDemand: 85,
    proficiency: 2,
  },
  {
    id: "si6",
    name: "REST API Design",
    category: "Backend",
    currentLevel: "Intermediate",
    targetLevel: "Advanced",
    priority: "High",
    estimatedTime: "1-2 months",
    description: "RESTful API design principles and best practices",
    marketDemand: 88,
    proficiency: 3,
  },
  {
    id: "si7",
    name: "Docker Compose",
    category: "DevOps",
    currentLevel: "Beginner",
    targetLevel: "Intermediate",
    priority: "Medium",
    estimatedTime: "1-2 months",
    description: "Multi-container Docker application orchestration",
    marketDemand: 80,
    proficiency: 2,
  },
  {
    id: "si8",
    name: "Git Workflows",
    category: "Tools",
    currentLevel: "Beginner",
    targetLevel: "Intermediate",
    priority: "Medium",
    estimatedTime: "1 month",
    description: "Advanced Git workflows and branching strategies",
    marketDemand: 90,
    proficiency: 2,
  },
  {
    id: "si9",
    name: "Python",
    category: "Language",
    currentLevel: "Intermediate",
    targetLevel: "Advanced",
    priority: "Medium",
    estimatedTime: "2-3 months",
    description: "Deep dive into advanced Python concepts",
    marketDemand: 88,
    proficiency: 3,
  },
  {
    id: "si10",
    name: "Agile/Scrum",
    category: "Methodology",
    currentLevel: "Beginner",
    targetLevel: "Intermediate",
    priority: "Low",
    estimatedTime: "1 month",
    description: "Agile methodologies and sprint-based development",
    marketDemand: 85,
    proficiency: 2,
  },
  {
    id: "si11",
    name: "Problem Solving",
    category: "Soft Skills",
    currentLevel: "Intermediate",
    targetLevel: "Advanced",
    priority: "High",
    estimatedTime: "3-4 months",
    description: "Algorithmic problem solving and DSA",
    marketDemand: 92,
    proficiency: 3,
  },
  {
    id: "si12",
    name: "API Testing",
    category: "QA",
    currentLevel: "Beginner",
    targetLevel: "Intermediate",
    priority: "Medium",
    estimatedTime: "1-2 months",
    description: "Testing strategies for APIs and endpoints",
    marketDemand: 80,
    proficiency: 2,
  },
]

// MATCHING SKILLS DATA - Skills user has at target proficiency
export const MATCHING_SKILLS_POOL = [
  {
    id: "ms1",
    name: "JavaScript",
    category: "Language",
    yourLevel: "Expert",
    matchQuality: "Exact Match",
    marketDemand: 95,
    proficiency: 4.5,
  },
  {
    id: "ms2",
    name: "HTML/CSS",
    category: "Frontend",
    yourLevel: "Advanced",
    matchQuality: "Exact Match",
    marketDemand: 90,
    proficiency: 4,
  },
  {
    id: "ms3",
    name: "Git",
    category: "Tools",
    yourLevel: "Advanced",
    matchQuality: "Exact Match",
    marketDemand: 93,
    proficiency: 4,
  },
  {
    id: "ms4",
    name: "Problem Solving",
    category: "Soft Skills",
    yourLevel: "Advanced",
    matchQuality: "Exact Match",
    marketDemand: 92,
    proficiency: 4,
  },
  {
    id: "ms5",
    name: "Communication",
    category: "Soft Skills",
    yourLevel: "Advanced",
    matchQuality: "Exact Match",
    marketDemand: 88,
    proficiency: 4,
  },
  {
    id: "ms6",
    name: "Data Structures & Algorithms",
    category: "Fundamentals",
    yourLevel: "Advanced",
    matchQuality: "Exact Match",
    marketDemand: 90,
    proficiency: 4,
  },
  {
    id: "ms7",
    name: "SQL",
    category: "Database",
    yourLevel: "Advanced",
    matchQuality: "Exact Match",
    marketDemand: 88,
    proficiency: 4,
  },
  {
    id: "ms8",
    name: "JSON/XML",
    category: "Data Formats",
    yourLevel: "Expert",
    matchQuality: "Exact Match",
    marketDemand: 85,
    proficiency: 4.5,
  },
  {
    id: "ms9",
    name: "Debugging",
    category: "Tools",
    yourLevel: "Advanced",
    matchQuality: "Exact Match",
    marketDemand: 87,
    proficiency: 4,
  },
  {
    id: "ms10",
    name: "API Design & REST",
    category: "Backend",
    yourLevel: "Advanced",
    matchQuality: "Exact Match",
    marketDemand: 88,
    proficiency: 4,
  },
  {
    id: "ms11",
    name: "Postman/API Testing",
    category: "Tools",
    yourLevel: "Advanced",
    matchQuality: "Exact Match",
    marketDemand: 82,
    proficiency: 4,
  },
  {
    id: "ms12",
    name: "Linux/Unix",
    category: "System",
    yourLevel: "Intermediate",
    matchQuality: "Partial Match",
    marketDemand: 85,
    proficiency: 3.5,
  },
  {
    id: "ms13",
    name: "Responsive Design",
    category: "Frontend",
    yourLevel: "Advanced",
    matchQuality: "Exact Match",
    marketDemand: 87,
    proficiency: 4,
  },
  {
    id: "ms14",
    name: "Version Control",
    category: "Tools",
    yourLevel: "Advanced",
    matchQuality: "Exact Match",
    marketDemand: 90,
    proficiency: 4,
  },
  {
    id: "ms15",
    name: "Documentation",
    category: "Soft Skills",
    yourLevel: "Advanced",
    matchQuality: "Exact Match",
    marketDemand: 80,
    proficiency: 4,
  },
  {
    id: "ms16",
    name: "Code Review",
    category: "Soft Skills",
    yourLevel: "Advanced",
    matchQuality: "Exact Match",
    marketDemand: 85,
    proficiency: 4,
  },
  {
    id: "ms17",
    name: "Mentoring",
    category: "Soft Skills",
    yourLevel: "Intermediate",
    matchQuality: "Partial Match",
    marketDemand: 78,
    proficiency: 3.5,
  },
]

/**
 * Helper function to generate random selection from pools
 */
function getRandomItems<T>(array: T[], count: number): T[] {
  const shuffled = [...array].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, Math.min(count, array.length))
}

/**
 * Generate random gap analysis data for mock display
 * Returns 10-15 critical gaps, 8-12 skills to improve, 12-18 matching skills
 */
export function generateMockGapAnalysisResults() {
  const criticalGaps = getRandomItems(CRITICAL_GAPS_POOL, 12)
  const skillsToImprove = getRandomItems(SKILLS_TO_IMPROVE_POOL, 10)
  const matchingSkills = getRandomItems(MATCHING_SKILLS_POOL, 15)

  // Calculate match score: base 70%, adjust based on gaps
  const baseScore = 70
  const gapPenalty = criticalGaps.length * 3
  const matchBonus = matchingSkills.filter((s) => s.yourLevel === "Expert").length * 2
  const overallMatchScore = Math.max(40, Math.min(95, baseScore - gapPenalty + matchBonus))

  return {
    analyzed: true,
    overallMatchScore,
    criticalGaps: criticalGaps.map((skill) => ({
      ...skill,
      insight: `${skill.priority === "Critical" ? "Critical" : "Important"} skill gap. Build foundational knowledge to advance in this position. Market demand is very high.`,
    })),
    skillsToImprove: skillsToImprove.map((skill) => ({
      ...skill,
      insight: `Advance from ${skill.currentLevel} to ${skill.targetLevel}. Your current proficiency needs development. Focus on practical application and real-world projects.`,
    })),
    matchingSkills: matchingSkills.map((skill) => ({
      ...skill,
      insight: `Strong match! Your ${skill.yourLevel} level in ${skill.name} aligns well with role expectations. Maintain and expand your expertise in this area.`,
    })),
  }
}
